export const AFF = {
  kayak: process.env.NEXT_PUBLIC_KAYAK_PARTNERID || 'demo_partner',
  skyscanner: process.env.NEXT_PUBLIC_SKYSCANNER_AFFID || 'aff_demo',
  trip: process.env.NEXT_PUBLIC_TRIP_AID || '99999',
  booking: process.env.NEXT_PUBLIC_BOOKING_AID || '1234567',
  agoda: process.env.NEXT_PUBLIC_AGODA_CID || '1234567',
  expedia: process.env.NEXT_PUBLIC_EXPEDIA_CAMPAIGN || 'demo-campaign',
  hotels: process.env.NEXT_PUBLIC_HOTELS_CAMPAIGN || 'demo-campaign',
  gflights: process.env.NEXT_PUBLIC_GOOGLE_FLIGHTS_TAG || 'aff',
  priceline: process.env.NEXT_PUBLIC_PRICELINE_PID || 'pid_demo',
  kiwi: process.env.NEXT_PUBLIC_KIWI_AFFID || 'kiwi_aff',
  gyg: process.env.NEXT_PUBLIC_GYG_AFFID || 'gyg_demo',
  tiqets: process.env.NEXT_PUBLIC_TIQETS_AFFID || 'tiq_demo',
  rentalcars: process.env.NEXT_PUBLIC_RENTALCARS_AFFID || 'rc_demo',
  discovercars: process.env.NEXT_PUBLIC_DISCOVERCARS_AFFID || 'dc_demo',
  trainline: process.env.NEXT_PUBLIC_TRAINLINE_AFFID || 'tl_demo',
  viator: process.env.NEXT_PUBLIC_VIATOR_AFFID || 'viator_demo',
  klook: process.env.NEXT_PUBLIC_KLOOK_AFFID || 'klook_demo',
};
